import Head from 'next/head'
import Landing from '../components/Landing'
import NavBar from '../components/navBar/NavBar'
import Transform from '../components/Transform'
import Stand from '../components/Stand'
import Graphic from '../components/Graphic'
import Client from '../components/Client'
import SunnySideImg from '../components/SunnySideImg'
import FooterSunny from '../components/FooterSunny'

export default function Home() {
  return (
    <div className="w-screen box-border	">
      <Head>
        <title>sunnyside</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Landing />
      <Transform />
      <Stand />
      <Graphic />
      <Client />
      <SunnySideImg />
      <FooterSunny />
    </div>
  )
}
